### ISSUE TITLE
SPMC and OSMC support for python_libtorrent

### ISSUE THREAD

**Issue by ronniehd** [DiMartinoXBMC/script.module.libtorrent#7]
Hello, in Android with SPMC installed when i click on python-libtorrent add-on i get the following error:
`OS:android arch:arm
Failed to import python-libtorrent!`

I've done my research and modified script.module.libtorrent\python_libtorrent\python_libtorrent\__init__.py file to replace 'org.xmbc.kodi/lib/' for '/data/data/com.semperpax.spmc16/lib/' but the error still remains. So reading some more i found that the add-on while importing liblibtorrent.so, it calls libkodi.so which is not found and needed by liblibtorrent.so because in SPMC instead there is libspmc.so and for OSMC i think it is called libxbmc.so and for the life of me don't know where and how to change that (it goes beyond my limited knowledge).

Hope you can help me out with this. Thank you in advance! 
V

**Comment by DiMartinoXBMC** [comment]
I don't compile python-libtorrent for Android, but I know from guys who do it, that you have to link "libkodi.so" to get it work on device with libkodi.so. We chose to compile only version with "libkodi.so" because it's a standart, but you can compile it with any link that you need.
[Here is bash script](https://drive.google.com/drive/folders/0B-8jsQlCcIFzczR0OVQzS1A3bFU) from srg70, but you would need to edit a bit for your configuration. If you manage to compile it properly I'll consider adding it to addon with regex that determine this OS.
Advice from him: android toolcahing should be in /opt
